name: Testing
on: push
env:
  TEST_SECRET_1: ${{ secrets.TEST_SECRET_1 }}
  TEST_SECRET_2: ${{ secrets.TEST_SECRET_2 }}
  TEST_SECRET_3: ${{ secrets.TEST_SECRET_3 }}
  TEST_SECRET_4: ${{ secrets.TEST_SECRET_4 }}
  TEST_SECRET_5: ${{ secrets.TEST_SECRET_5 }}

jobs:
  unit-test:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm ci
      - run: npm test

  integration-test-script:
    name: Integration::Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash build.sh
        working-directory: ./fixtures/script
      - name: run check-secrets
        id: test
        uses: ./
        continue-on-error: true
        with:
          secrets: |
            TEST_SECRET_1: ${{ secrets.TEST_SECRET_1 }}
            TEST_SECRET_2: ${{ secrets.TEST_SECRET_2 }}
            TEST_SECRET_3: ${{ secrets.TEST_SECRET_3 }}
          patterns: fixtures/script/**
      - name: check test failed
        if: steps.test.outcome != 'failure'
        run: echo -e "Integration::Script \e[91mFailed\e[39m (expected) ✅"




